export const taskBoardsActionType = {
  GET_TASK_STATUS: 'GET_TASK_STATUS',
  SET_LOADING: 'SET_LOADING',
  HIDE_LOADER_LIST: 'HIDE_LOADER_LIST',
  FILTERING_TASK_BY_USER: 'FILTERING_TASK_BY_USER',
  GET_TASK_STATUS_BY_ID: 'GET_TASK_STATUS_BY_ID',
  GET_TASK_BOARD: 'GET_TASK_BOARD',
  SET_SELECTED_TASKBOARD: 'SET_SELECTED_TASKBOARD',
  HAS_NO_DATA: 'HAS_NO_DATA',
  CREATE_TASK_BOARD: 'CREATE_TASK_BOARD',
  CREATE_TASK_STATUS: 'CREATE_TASK_STATUS',
};
