export const boardsActionType = {
  GET_LIST_BOARDS: 'GET_LIST_BOARDS',
  SET_BOARD: 'SET_BOARD',
  CREATE_BOARD: 'CREATE_BOARD',
  UPDATE_NAME_FLOWCHART: 'UPDATE_NAME_FLOWCHART',
  DELETE_BOARD: 'DELETE_BOARD',
  SHOW_LOADER_LIST: 'SHOW_LOADER_LIST',
  HIDE_LOADER_LIST: 'HIDE_LOADER_LIST',
  HAS_NO_DATA: 'HAS_NO_DATA',
};
