export const boardsActionType = {
  GET_LIST_BOARDS: 'GET_LIST_BOARDS',
  SET_BOARD: 'SET_BOARD',
  CREATE_BOARD: 'CREATE_BOARD',
  UPDATE_NAME_FLOWCHART: 'UPDATE_NAME_FLOWCHART',
  DELETE_BOARD: 'DELETE_BOARD',
  UPDATE_CARDS: 'UPDATE_CARDS',
};
