export enum Roles {
  ADMIN = 'ADMIN',
  COMPANY_MANAGER = 'COMPANY_MANAGER',
  COMPANY_STAFF = 'COMPANY_STAFF',
  DEPARTMENT_MANAGER = 'DEPARTMENT_MANAGER',
  DEPARTMENT_STAFF = 'DEPARTMENT_STAFF',
}
