export const statisticsAction = {
  GET_LIST_CHECKIN_CHECKOUT: 'GET_LIST_CHECKIN_CHECKOUT',
  CHECKIN_CHECKOUT_CURSOR: 'CHECKIN_CHECKOUT_CURSOR',
  SELECTED_USERID: 'SELECTED_USERID',
  LIMIT_TRACKING: 'LIMIT_TRACKING',
}
