# need to set up in gitlab ci variables:
# @ GIT_REPO
# @ DEPLOY_AWS_PRIVATE_KEY
# @ DEPLOY_GIT_PRIVATE_KEY
# @ DEV_INSTANCE_IP
# @ PROD_INSTANCE_IP

image: ubuntu

variables:
  S3_BUCKET_NAME_STAGING: "snt-web-app-staging"
  S3_BUCKET_NAME_PRODUCTION: "snt-web-app-production"
  ## todo: create s3 production bucket
stages:
  - test
  - staging
  - production

test:
  stage: test
  script:
    - . ops/git_init.sh
    - npm install
    - npm i serve
    - npm run linter-folder
    - npm run tslint
    - npm run build
    - npm run static --silent &
    - . ops/wait_apis.sh
    - npm run test -- -u
    - . ops/git_push_build.sh
  only:
    - branches
  except:
    refs:
      - master
      - dev

staging:
  stage: dev-test-build
  script:
    - . ops/git_init.sh
    - npm install
    - npm i serve
    - npm run linter-folder
    - npm run build
    - npm run static --silent &
    - . ops/wait_apis.sh
    - npm run test -- -u
    - . ops/install_aws_cli.sh
    - aws s3 cp ./out/ s3://$S3_BUCKET_NAME_STAGING/ --recursive --exclude "*" --include "*.html"
  only:
    - master

production:
  stage: production
  script:
    - . ops/git_init.sh
    - npm install
    - npm i serve
    - npm run linter-folder
    - npm run build
    - npm run static --silent &
    - . ops/wait_apis.sh
    - npm run test -- -u
    - . ops/install_aws_cli.sh
    - aws s3 cp ./out/ s3://$S3_BUCKET_NAME_PRODUCTION/ --recursive --exclude "*" --include "*.html"
  only:
    - tags

