export const taskCommentsActionType = {
  SET_LOADING: 'SET_TASK_COMMENT_LOADING',
  GET_TASK_COMMENTS: 'GET_TASK_COMMENTS',
  SET_TEMPORARY_COMMENT: 'SET_TEMPORARY_COMMENT',
  ADD_TASK_COMMENT: 'ADD_TASK_COMMENT',
  UPDATE_TASK_COMMENT: 'UPDATE_TASK_COMMENT',
  DELETE_TASK_COMMENT: 'DELETE_TASK_COMMENT',
  SET_TASK_COMMENT: 'SET_TASK_COMMENT',
}
