export const dashboardClickUp = {
  GET_TASK_STATUSES: 'GET_TASK_STATUSES',
  SHOW_LOADER_LIST: 'SHOW_LOADER_LIST',
  HIDE_LOADER_LIST: 'HIDE_LOADER_LIST',
  GET_TASK: 'GET_TASK',
  GET_TASK_STATUS_BY_ID: 'GET_TASK_STATUS_BY_ID',
  SET_TASKS_TO_TASK_STATUS: 'SET_TASKS_TO_TASK_STATUS',
  UPDATE_TASKS_TO_TASK_STATUS: 'UPDATE_TASKS_TO_TASK_STATUS',
  SET_SELECTED_TASK: 'SET_SELECTED_TASK',
};
