export const dashboardClickUp = {
  GET_TASK_STATUSES: 'GET_TASK_STATUSES',
  SHOW_LOADER_LIST: 'SHOW_LOADER_LIST',
  HIDE_LOADER_LIST: 'HIDE_LOADER_LIST',
  GET_TASK: 'GET_TASK',
  GET_TASK_STATUS_BY_ID: 'GET_TASK_STATUS_BY_ID',
  ADD_TASK: 'ADD_TASK',
  SET_TYPE_CREATE_TASK: 'SET_TYPE_CREATE_TASK',
};
