export const dashboardClickUp = {
  GET_TASK_STATUSES: 'GET_TASK_STATUSES',
  SET_LOADING: 'SET_LOADING',
  HIDE_LOADER_LIST: 'HIDE_LOADER_LIST',
  GET_TASK_BY_USER_ID: 'GET_TASK_BY_USER_ID',
  GET_TASK_STATUS_BY_ID: 'GET_TASK_STATUS_BY_ID',
  GET_TASK_BOARD: 'GET_TASK_BOARD',
  GET_TASK_BOARD_BY_ID: 'GET_TASK_BOARD_BY_ID',
  SET_SELECTED_TASKBOARD: 'SET_SELECTED_TASKBOARD',
  HAS_NO_DATA: 'HAS_NO_DATA',
  CREATE_TASK_BOARD: 'CREATE_TASK_BOARD',
};
