export const projectsActionType = {
  GET_LIST_PROJECTS: 'GET_LIST_PROJECTS',
  GET_PROJECT: 'GET_PROJECT',
  SET_SELECTED_CHANNEL_ID: 'SET_SELECTED_CHANNEL_ID',
  UPDATE_CHANNEL_ID: 'UPDATE_CHANNEL_ID',
  GET_CHANNELS_BY_COMPANY: 'GET_CHANNELS_BY_COMPANY',
  UPDATE_RESULT_INFO: 'UPDATE_RESULT_INFO',
  SHOULD_SHOW_DESCRIPTION: 'SHOULD_SHOW_DESCRIPTION',
};
