export const taskActionType = {
  GET_TASKS: 'GET_TASKS',
  SET_LOADING: 'SET_LOADING',
  SET_TEMPORARY_TASK: 'SET_TEMPORARY_TASK',
  SET_ASSIGNED: 'SET_ASSIGNED',
  SET_CURRENT_STATUS: 'SET_CURRENT_TASK',
  CREATE_TASK: 'CREATE_TASK',
  UPDATE_TASK: 'UPDATE_TASK',
  DELETE_TASK: 'DELETE_TASK',
  SET_SELECTED_TITLE: 'SET_SELECTED_TITLE',
  SET_SELECTED_USERS: 'SET_SELECTED_USERS',
  SET_SELECTED_TAGS: 'SET_SELECTED_TAGS',
};
