export const usersAction = {
  GET_LIST_USERS: 'GET_LIST_USERS',
  USER_CURSOR: 'USER_CURSOR',
  SHOW_LOADER_LIST: 'SHOW_LOADER_LIST',
  HIDE_LOADER_LIST: 'HIDE_LOADER_LIST',
  PAGINATION: 'PAGINATION',
  SEARCH: 'SEARCH',
  GET_NOTIFICATIONS: 'GET_NOTIFICATIONS',
  HAS_NO_NOTIFICATION: 'HAS_NO_NOTIFICATION',
};
