export const usersAction = {
  GET_LIST_USERS: 'GET_LIST_USERS',
  USER_CURSOR: 'USER_CURSOR',
  SET_LOADING: 'SET_LOADING',
  PAGINATION: 'PAGINATION',
  SEARCH: 'SEARCH',
  GET_NOTIFICATIONS: 'GET_NOTIFICATIONS',
  HAS_NO_NOTIFICATION: 'HAS_NO_NOTIFICATION',
  UPDATE_NOTIFICATION: 'UPDATE_NOTIFICATION',
};
