export const eventLogsAction = {
  GET_EVENT_LOGS: 'GET_EVENT_LOGS',
  GET_EVENT_LOG: 'GET_EVENT_LOG',
  EVENT_LOG_CURSOR: 'EVENT_LOG_CURSOR',
  SHOW_LOADER_LIST: 'SHOW_LOADER_LIST',
  HIDE_LOADER_LIST: 'HIDE_LOADER_LIST',
  SET_SELECTED_ENV: 'SET_SELECTED_ENV',
  SET_SELECTED_TIME: 'SET_SELECTED_TIME',
  SET_SELECTED_PROJECTID: 'SET_SELECTED_PROJECTID',
  HAS_NO_DATA: 'HAS_NO_DATA',
}
