export const taskStatusesActionType = {
  GET_STATUS_BY_ID: 'GET_STATUS_BY_ID',
  RENAME_STATUS: 'RENAME_STATUS',
  SET_TEMP_TITLE_STATUS: 'SET_TEMP_TITLE_STATUS',
  DELETE_STATUS: 'DELETE_STATUS',
  CREATE_STATUS: 'CREATE_STATUS',
  SET_LOADING: 'SET_TASK_STATUS_LOADING',
  SET_CURRENT_STATUS: 'SET_CURRENT_STATUS',
  SET_TASKS_TO_STATUS: 'SET_TASKS_TO_STATUS',
  REMOVE_TASK_FROM_STATUS: 'REMOVE_TASK_FROM_STATUS',
}
